name: dagster-mlflow
channels:
  - defaults
  - conda-forge
  - bokeh
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - alembic
  - aniso8601
  - appdirs
  - argh
  - asn1crypto
  - attrs
  - azure-core
  - azure-storage-blob
  - black
  - bleach
  - blinker
  - brotlipy
  - c-ares
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - click
  - cloudpickle
  - coloredlogs
  - configparser
  - contextlib2
  - croniter
  - cryptography
  - dagit
  - dagster
  - dagster-graphql
  - databricks-cli
  - dataclasses
  - defusedxml
  - docker-py
  - docker-pycreds
  - docstring_parser
  - entrypoints
  - enum-compat
  - flask
  - flask-cors
  - flask-graphql
  - flask-sockets
  - funcsigs
  - future
  - gevent
  - gevent-websocket
  - gitdb
  - gitpython
  - gorilla
  - graphene
  - graphql-core
  - graphql-relay
  - graphql-server-core
  - graphql-ws
  - greenlet
  - grpcio
  - grpcio-health-checking
  - gunicorn
  - humanfriendly
  - idna
  - importlib-metadata
  - importlib_metadata
  - ipython_genutils
  - isodate
  - itsdangerous
  - jinja2
  - joblib
  - jsonschema
  - jupyter_core
  - ld_impl_linux-64
  - libblas
  - libcblas
  - libev
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran4
  - libgomp
  - liblapack
  - libopenblas
  - libprotobuf
  - libstdcxx-ng
  - libuv
  - mako
  - markupsafe
  - mistune
  - mlflow
  - msrest
  - mypy_extensions
  - natsort
  - nbconvert
  - nbformat
  - ncurses
  - numpy
  - oauthlib
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - pathspec
  - pendulum
  - pip
  - prometheus_client
  - prometheus_flask_exporter
  - promise
  - protobuf
  - pycparser
  - pygments
  - pyjwt
  - pyopenssl
  - pyparsing
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python-editor
  - python_abi
  - pytz
  - pytzdata
  - pyyaml
  - querystring_parser
  - readline
  - regex
  - requests
  - requests-oauthlib
  - rx
  - scikit-learn
  - scipy
  - setuptools
  - six
  - smmap
  - sqlalchemy
  - sqlite
  - sqlparse
  - tabulate
  - testpath
  - threadpoolctl
  - tk
  - toml
  - toposort
  - tqdm
  - traitlets
  - typed-ast
  - typing_extensions
  - tzdata
  - tzlocal
  - urllib3
  - watchdog
  - webencodings
  - websocket-client
  - werkzeug
  - wheel
  - xz
  - yaml
  - zipp
  - zlib
  - zope
  - zope.event
  - zope.interface
  