name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - sqlalchemy
  - sqlite
  - mlflow
  - psycopg2
  - pysftp
  - boto3
  - dagster
  - dagster-postgres
  - dagster-docker
  - pandas
  - scikit-learn 
  # - p
    # - onnx==1.6.0
    # - onnxruntime==1.1.0
    # - onnxmltools==1.6.0
    # - skl2onnx==1.6.0
    # - sklearn